### ISSUE TITLE
Notification always shows "Success!"

### ISSUE THREAD

**Issue by lourenco00** [Skitionek/notify-microsoft-teams#30]
![imagem](https://user-images.githubusercontent.com/91602746/180260011-59939c40-6b85-4ca7-bc06-473e18abe55e.png)
As you can see, even though one of the steps before this job having failed the notification appears as "Success!" and with green color.
How can I fix this to when there's a job that fails appear "failure" and red color?
I'll paste here my code:
![imagem](https://user-images.githubusercontent.com/91602746/180260330-bc7c362d-7c99-4a51-b621-89022d4df5ef.png)

**Comment by vml-loshea** [comment]
If I understand how this tool works, you are getting a success because the job containing the notification (named success I think) always runs, and that job succeeds.  I think the notification tool only reports as success or failure the results of the job it is included in.  So if you want it to report the job status based on the results of the deployAnsible job, you need to put the skitionek/notify-microsoft-teams step in the deployAnsible job.

I don't see anywhere else where the code decides success or failure if any of the needs jobs are failures.

**Comment by Skitionek** [comment]
@vml-loshea that's right
